name: "Documentation feedback or issue"
description: Report any issues or share suggestions for improving our documentation
labels: 
- Documentation
body:
- id: description
  type: textarea
  attributes: 
    label: Provide a description of requested docs changes
    placeholder: Briefly describe which document needs to be corrected and why.
  validations:
    required: true
